name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    if: ${{ github.repository == 'xopt-org/xopt' }}
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  dispatch-deploy-docs:
    needs: build-n-publish
    name: Dispatch deploy docs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -qs \
          --fail-with-body \
          -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_DOCS }}" \
          https://api.github.com/repos/xopt/Xopt-docs/dispatches \
          -d '{"event_type":"release"}'
